---
title: "no-deadline Srtoop: creating raw data from source"
author: "Zsuzsa Szekely"
date: '2021 12 01 '
output: html_document
---

# Load packages

```{r load packages}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, janitor, jsonlite, rlist)
```

# Load helper functions

```{r load helper functions}
source("R/utils.R")
```

# Import and merge data

```{r import and merge data}
# Read in datafiles from json to a tibble
source <- read_json_to_tibble("data/deadline/source/")

# Calculate the number of rows and columns
source <- 
  source %>%
  mutate(col_names = map(parsed_df, colnames),
         col_num = map_int(parsed_df, length),
         row_num = map_int(parsed_df, nrow),
         filename = map_chr(parsed_df, ~unique(.x[["participant"]])))

# Check the distribution of the number of responses per column per row
source %>%
  count(col_num, row_num)

# Filter and merge the number of datafiles with 26 columns
source_filtered <- 
  source %>% 
  filter(col_num == 26 & row_num == 319) %>% 
  select(parsed_df)

source_filtered <- bind_rows(source_filtered$parsed_df)

# Clean participant id
source_filtered <- 
  source_filtered %>% 
  group_by(participant) %>% 
  mutate(participant = cur_group_id()) %>% 
  arrange(participant)
```

# Join data with participant_id...

# Deidentify participants

We need to remove any information that might identify the participants

```{r deidentify participants}
# join <- 
#   join %>% 
#   mutate(join = select(., -userId))
```

# Save each task separately

```{r save tasks}
write_tsv(source, file = ("deadline/data/raw/raw_data.tsv"))
```

Final tsv files were uploaded to OSF manually.